name: CI - Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install MKVToolNix
        run: |
          sudo apt-get update
          sudo mkdir -p /etc/apt/keyrings
          sudo wget -O /etc/apt/keyrings/mkvtoolnix.gpg https://mkvtoolnix.download/gpg-pub-moritzbunkus.gpg
          echo "deb [signed-by=/etc/apt/keyrings/mkvtoolnix.gpg] https://mkvtoolnix.download/ubuntu/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/mkvtoolnix.list
          sudo apt-get update
          sudo apt-get install -y mkvtoolnix

      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends build-essential pkg-config clang
          sudo apt-get install -y libleptonica-dev libtesseract-dev tesseract-ocr libfuse2

      - name: Install Rust Toolchain (Stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Run Build Script
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SubtitleConverter-AppImage
          path: SubtitleConverter-x86_64.AppImage

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./SubtitleConverter-x86_64.AppImage
          asset_name: SubtitleConverter-x86_64.AppImage
          asset_content_type: application/octet-stream